### ISSUE TITLE
Duping of katanas that drop as entities. (1.7.10)

### ISSUE THREAD

**Issue by dechiexe** [coolsimulations/FloatingItems#1]
When using FloatingItems together with SlashBlade, katanas that drop as blade stands (entities you can right click to pick back up) will duplicate themselves.

Video of expected behavior (only slashblade enabled):
[No FloatingItems.webm](https://github.com/coolsimulations/FloatingItems/assets/136037772/e8a0f5e8-6bf8-44aa-ad2f-9fd63b47a7cd)

Video of bug: (floatingitems and slashblade enabled):
[FloatingItems.webm](https://github.com/coolsimulations/FloatingItems/assets/136037772/e0a0bbe6-6ed0-4fab-9315-e427d368f4dd)

Modlist:
![image](https://github.com/coolsimulations/FloatingItems/assets/136037772/11f258b4-0112-45f0-b990-da2d7ebc75d4)

Log File: [fml-client-latest.log](https://github.com/coolsimulations/FloatingItems/files/11699432/fml-client-latest.log)

**Comment by coolsimulations** [comment]
What you should be able to do is add the affected item IDs to the FloatingItems blacklist in the config file. Hopefully, that will work, let me know if otherwise though.

**Comment by dechiexe** [comment]
That did not end up working, unless I did the configuration wrong.

![image](https://github.com/coolsimulations/FloatingItems/assets/136037772/ec975c6d-cf40-4090-a57c-83a48f3cf840)

![2023-06-08_18 55 47](https://github.com/coolsimulations/FloatingItems/assets/136037772/c378852c-3ffa-43bb-a4f7-6bea2495d4f2)
